import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./_sections/providers";
import Motion from "./_sections/motion";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "./_sections/navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={` ${inter.variable} antialiased`}>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {" "}
            <Navbar />
            <div className="pt-16 min-h-screen">
              {/* Add padding to account for the fixed navbar */}
              <Motion>{children}</Motion>
            </div>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
